"""``turbo raycast`` — keep the Raycast extension's commands in sync with workflows."""

from __future__ import annotations

import json
import os
from pathlib import Path

import click

from turbollm.plugins.mac._common import console
from turbollm.registry import load_registry

_RAYCAST_FIXED_COMMANDS = {"run-workflow", "running-workflows"}


def _to_title_case(slug: str) -> str:
    """Convert a kebab-case slug to Title Case. E.g. 'transcribe-file' → 'Transcribe File'."""
    return " ".join(word.capitalize() for word in slug.split("-"))


@click.group(name="raycast")
def raycast_grp():
    """Raycast extension helpers."""


def _do_raycast_sync(extension_dir: Path, quiet: bool) -> None:
    """Business logic for `turbo raycast sync`. Also called by `turbo sidecar`."""
    from turbollm import workflows as _wf

    reg = load_registry()
    wf_items = []
    for name, wf in _wf.load_workflows(reg).items():
        try:
            _wf.validate_workflow(name, wf)
        except _wf.WorkflowError:
            continue
        wf_items.append({"name": name, **wf})

    pkg_path = Path(extension_dir) / "package.json"
    if pkg_path.exists():
        pkg = json.loads(pkg_path.read_text())
    else:
        pkg = {}

    commands = pkg.get("commands", [])
    fixed_commands = [cmd for cmd in commands if cmd.get("name") in _RAYCAST_FIXED_COMMANDS]

    # Raycast's Swift Codable decoder requires `description` and `mode` on every
    # command entry; omitting either causes "Could not install extension from
    # development sources" / "No value associated with key description" failures.
    # Use the workflow's description for both `subtitle` (UI hint) and
    # `description` (required by decoder).
    wf_commands = sorted(
        [
            {
                "name": wf["name"],
                "title": _to_title_case(wf["name"]),
                "subtitle": wf.get("description", ""),
                "description": wf.get("description", "") or _to_title_case(wf["name"]),
                "mode": "view",
            }
            for wf in wf_items
        ],
        key=lambda c: c["name"],
    )

    pkg["commands"] = fixed_commands + wf_commands
    output = json.dumps(pkg, indent=2) + "\n"
    pkg_path.write_text(output)

    # --- Per-workflow symlinks + _generated_commands.ts ---
    src_dir = Path(extension_dir) / "src"
    src_dir.mkdir(parents=True, exist_ok=True)

    wf_names = {wf["name"] for wf in wf_items}

    # Per-workflow command files. Originally symlinks to run-workflow.tsx, but
    # Raycast's bundler de-dupes symlinks (multiple commands collapsing to one
    # compiled JS file), causing "Could not find command's executable JS file"
    # at runtime. Use thin re-export stubs instead — each stub is a real file
    # so the bundler emits a distinct JS artifact per command.
    stub_marker = "// turbo raycast sync — per-workflow re-export stub"
    stub_body = (
        f"{stub_marker}\n"
        "// Logic lives in run-workflow.tsx; this file just re-exports the default\n"
        "// component so Raycast's bundler emits a distinct compiled JS per command.\n"
        'export { default } from "./run-workflow";\n'
    )

    for wf_name in wf_names:
        link = src_dir / f"{wf_name}.tsx"
        if link.is_symlink():
            # Migrate legacy symlinks to stubs.
            link.unlink()
            link.write_text(stub_body)
        elif not link.exists():
            link.write_text(stub_body)
        # If it's a real non-stub file (user-authored or our stub), leave alone.

    # Remove orphan stub/symlink files — those whose workflow slug is no longer
    # in the registry. Identify ours by either symlink target or stub marker.
    for tsx_file in src_dir.glob("*.tsx"):
        if tsx_file.stem in wf_names or tsx_file.stem in {"run-workflow", "running-workflows"}:
            continue
        is_legacy_symlink = tsx_file.is_symlink() and os.readlink(str(tsx_file)) == "run-workflow.tsx"
        is_stub = tsx_file.is_file() and stub_marker in tsx_file.read_text()
        if is_legacy_symlink or is_stub:
            tsx_file.unlink()

    # Write src/_generated_commands.ts — a type-safe command-name → workflow-name map.
    entries = "".join(
        f'  "{name}": "{name}",\n'
        for name in sorted(wf_names)
    )
    generated_ts = (
        "// Auto-generated by `turbo raycast sync`. Do not edit manually.\n"
        "export const GENERATED_COMMANDS: Record<string, string> = {\n"
        f"{entries}"
        "};\n"
    )
    gen_path = src_dir / "_generated_commands.ts"
    gen_path.write_text(generated_ts)

    if not quiet:
        console.print(
            f"[green]Synced[/green] {len(wf_commands)} workflow command(s) → {pkg_path}"
        )


@raycast_grp.command(name="sync")
@click.option(
    "--extension-dir",
    required=True,
    type=click.Path(file_okay=False, path_type=Path),
    help="Path to the Raycast extension directory (contains package.json).",
)
@click.option("--quiet", is_flag=True, help="Suppress output.")
def raycast_sync(extension_dir, quiet):
    """Regenerate Raycast package.json commands from the current workflow list.

    Preserves the fixed commands (run-workflow, running-workflows) and removes
    per-workflow commands that no longer appear in the workflow list.
    """
    _do_raycast_sync(Path(extension_dir), quiet)
