// Auto-generated by `turbo raycast sync`. Do not edit manually.
export const GENERATED_COMMANDS: Record<string, string> = {
  "record-to-obsidian": "record-to-obsidian",
  "transcribe-file": "transcribe-file",
};
