// Auto-generated by `turbo raycast sync`. Do not edit manually.
// Run `turbo raycast sync --extension-dir tools/raycast-turbo` to update.
export const GENERATED_COMMANDS: Record<string, string> = {};
