// Per-workflow command — emits a distinct compiled JS file so Raycast can
// route to it. Logic lives in run-workflow.tsx; this is a thin re-export.
// Generated by `turbo raycast sync`.
export { default } from "./run-workflow";
